version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4.1.4-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 9s

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  add_worker:
    build: ./arithmetic-system
    command: python -m app.workers.add_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

  sub_worker:
    build: ./arithmetic-system
    command: python -m app.workers.sub_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

  mul_worker:
    build: ./arithmetic-system
    command: python -m app.workers.mul_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

  div_worker:
    build: ./arithmetic-system
    command: python -m app.workers.div_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

  xsum_worker:
    build: ./arithmetic-system
    command: python -m app.workers.xsum_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

  xprod_worker:
    build: ./arithmetic-system
    command: python -m app.workers.xprod_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

  entrypoint:
    build: ./arithmetic-system
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure
